// formDataUtils.js
export const initializeFormData = (program) => {
  return {
    programService: program.ProgramService || '',
    presentation: program.Presentation || false,
    submittedCreateProgramming: program.submittedCreateProgramming || false,
    submittedWorldProgramming: program.submittedWorldProgramming || false,
    createPremiere: program.CreatePremiere || false,
    promoExpected: program.PromoExpected || false,
    promoComments: program.PromoComments || '',
    fundCategory: program.ProgramFund || '',
    screeningStatus: program.ScreeningStatus || '',
    copyrightDate: program.CopyrightDate || '',
    CopyrightHolder: program.CopyrightHolder || '',
    numOfEpisodes: program.NumberOfEpisodes || '',
    programLength: program.ProgramLength || '',
    containsFilters: program.ProgramService || false,
    category: program.Category || '',
    ptvGenre: program.PTVGenre || '',
    schedulingSuggestions: program.SchedulingSuggestions || '',
    nationalBasePrice: program.NationalBasePrice || '',
    video: program.Video || '',
    apsContact: program.APSContact || '',
    offerStatus: program.offerStatus || '',
    screeningTape: program.screeningTape || '',
    descriptionRoutingStatus: program.DescriptionRoutingStatus || '',
    seasonYear: program.SeasonYear || '',
    offeredVia: program.offeredVia || '',
    pageNumOfferBook: program.PageNumber || '',
    rating: program.Rating || '',
    usPremiere: program.USPremiere || false,
    contentAdvisory: program.ContentAdvisory || false,
    editFlags: program.EditFlags || false,
    flagUpdatedDate: program.FlagUpdatedDate || '',
    mmPotential: program.MMPotential || '',
    mmShortDesc: program.MMShortDesc || '',
    mmLongDesc: program.MMLongDesc || '',
    MMDescriptionsReviewed: program.MMDescriptionsReviewed || '',
    mmGenre: program.MMGenre || '',
    deliveryDate: program.DeliveryDate || '',
    releaseDate: program.ReleaseDate || '',
    contractStartDate: program.ContractStartDate || '',
    contractEndDate: program.ContractEndDate || '',
    contractExecuted: false,
    musicRecieved: false,
    licenseNum: '', // HUH?
    guaranteedPrice: program.GuaranteedPrice || '',
    licenseFee: '', // HUH?
    buyout: program.BuyOut || false,
    pricingStructure: program.PricingStructure || '',
    numLicensees: program.CurrentLicensees || '',
    currentLicenseFee: '', //HUH?
    addOns: program.AddOns || '',
    alerts: program.Alert || '',
    conversionCosts: program.ConversionCosts || false,
    supplierProvided: '', //HUH?
    durationPeriod: program.Duration || '',
    nationalUnderwriter: program.NationalUnderwriter || '',
    underwriters: program.UnderwrittenBy || '',
    localUnderwriting: program.LocalUnderwritingPermitted || false,
    localUnderwritingRestrictions: program.LocalUnderwritingRestrictions || '',
    format: program.Formats || '',
    ratio: program.Ratio || '',
    nola: program.Nola || '',
    sIXAvailability: program.sIXAvailability || '',
    episodeNum: program.EpisodeNumber || '',
    promoMaterials: '', //HUH?
    merchandiseInfoLink: program.DoclinkToMerchandise || '', // these seem to be objects
    viewerInquiries: {
      company: '',
      email: '',
      phoneNumber: '',
    },
    socialContact: {
      socialName: '',
      twitter: '',
      instagram: '',
      pinterest: '',
    },
    contractConfirmationDescription: program.ContractConfirmationDescription || '', // these seem to be objects
    borderStationsIncluded: false,
    mainContact: {
      company: '',
      streetAddress: '',
      city: '',
      country: '',
      zipCode: '',
      email: '',
      phoneNumber: '',
    },
    supplierContact: {
      company: '',
      streetAddress: '',
      city: '',
      country: '',
      zipCode: '',
      email: '',
      phoneNumber: '',
    },
    communicationsContact: {
      company: '',
      streetAddress: '',
      city: '',
      country: '',
      zipCode: '',
      email: '',
      phoneNumber: '',
    },
    operationsContact: {
      company: '',
      streetAddress: '',
      city: '',
      country: '',
      zipCode: '',
      email: '',
      phoneNumber: '',
    },
    producedPresentedBy: program.PresentedBy || '',
    stationRelationsContact: {
      company: '',
      streetAddress: '',
      city: '',
      country: '',
      zipCode: '',
      email: '',
      phoneNumber: '',
    },
    mediaContact: {
      company: '',
      streetAddress: '',
      city: '',
      country: '',
      zipCode: '',
      email: '',
      phoneNumber: '',
    },
    exportStatus1: false,
    exportStatus2: false,
    exportStatus3: false,
    numberOfInstallments: program.NumberOfInstallments || '',
    paymentToSupplier: program.PaymentToSupplier || '',
    billingStartDate: program.BillingStartDate || '',
    daysBetweenInstallments: program.DaysBetweenInstallments || ''
  }  
}  


