{
    "@meta": {
        "noteid": 2502,
        "unid": "0A79782628A79A7485258C070070FD13",
        "created": "2025-01-03T15:34:08.19-05:00",
        "lastmodified": "2025-01-03T15:34:08.22-05:00",
        "lastaccessed": "2025-01-03T15:37:11.02-05:00",
        "lastmodifiedinfile": "2025-01-03T15:37:11.03-05:00",
        "addedtofile": "2025-01-03T15:37:11.02-05:00",
        "noteclass": [
            "DATA",
            "DOCUMENT"
        ],
        "unread": false,
        "editable": true,
        "revision": "000000010070FD1685258C07",
        "etag": "W/\" 677849c0\"",
        "toplevelchildunids": [
            "6473B09DC3D7615285258C070070FD16",
            "8C6B63698CB707C385258C070070FD1A",
            "365AF915DD8E3BA185258C070070FD22",
            "D491C139D6937C4885258C070070FD17",
            "4286E6F423F0055A85258C070070FD1B",
            "EB5E5FDBCEF23EB085258C070070FD23",
            "1FB7E6CF6FFE532D85258C070070FD14",
            "E9DCB16CE00B904D85258C070070FD18",
            "990C8D686226AD9785258C070070FD24",
            "6171D76B744466A185258C070070FD15",
            "037BF3A3E58B147F85258C070070FD25"
        ],
        "size": 27086
    },
    "AdditionalMedia": "",
    "addOnCallSigns": [
        "WNMU"
    ],
    "AddOns": "Will Be Accepted",
    "Alert": "",
    "APExported": "No",
    "APSContact": "",
    "APSRevenueSharing": "",
    "ARExported": "No",
    "Audio": "Stereo",
    "Author": "Kendrick Terrell Evans",
    "AvailPubMaterials": "",
    "AwardPotential": "No",
    "BorderStationsExcluded": "",
    "BroadcastExclusivity": "Yes",
    "BroadcastHistory": "",
    "BroadcastRights": "Unlimited use/3 years",
    "BroadcastRights2": [
        ""
    ],
    "BuyOut": "",
    "Category": "Travel",
    "Checkout": "",
    "checkoutto": "",
    "Classification": "Series",
    "ClosedCaptioningFees": 0.0,
    "CommentsLiveStreamingInDiscuss": "",
    "CommentsLiveStreamingNo": "",
    "CommLearning": "",
    "CommLearningIdeas": "",
    "CommunicationsContact": "",
    "CommunicationsDocLink": {
        "type": "multipart/form-data",
        "topLevelType": "multipart/related",
        "encoding": "BASE64",
        "content": "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvcmVsYXRlZDsgYm91bmRhcnk9MC1mMTllNmQxYy04MzEyLTQ1NTctYjU3Yi1mNDU0OWE3NDc0OTcNCgotLTAtZjE5ZTZkMWMtODMxMi00NTU3LWI1N2ItZjQ1NDlhNzQ3NDk3CkNvbnRlbnQtdHlwZTogdGV4dC9odG1sOyBjaGFyc2V0PVVURi04CkNvbnRlbnQtRGlzcG9zaXRpb246IGlubGluZQo8aHRtbD4KIDxoZWFkPjwvaGVhZD4KIDxib2R5PjwvYm9keT4KPC9odG1sPgotLTAtZjE5ZTZkMWMtODMxMi00NTU3LWI1N2ItZjQ1NDlhNzQ3NDk3LS0K"
    },
    "ContentAdvisory": {
        "type": "multipart/form-data",
        "topLevelType": "multipart/related",
        "encoding": "BASE64",
        "content": "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvcmVsYXRlZDsgYm91bmRhcnk9MC01YzhhZThlNi1jOGIzLTQxMjYtYWYzNC1kMTQ4ZTFjZjc2YzMNCgotLTAtNWM4YWU4ZTYtYzhiMy00MTI2LWFmMzQtZDE0OGUxY2Y3NmMzCkNvbnRlbnQtdHlwZTogdGV4dC9odG1sOyBjaGFyc2V0PVVURi04CkNvbnRlbnQtRGlzcG9zaXRpb246IGlubGluZQo8aHRtbD4KIDxoZWFkPjwvaGVhZD4KIDxib2R5PgogIDxkaXYgY2xhc3M9ImRvbWluby1wYXItLWluZGVudCIgc3R5bGU9InBhZGRpbmctbGVmdDogMHB0OyBtYXJnaW4tbGVmdDogMHB4Ij4KICAgPHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBBcmlhbCA7IGZvbnQtc2l6ZTogMTBwdCA7IGZvbnQtd2VpZ2h0OiBib2xkIDsgIj4xMDAgREFZUywgRFJJTktTLCBESVNIRVMgJmFtcDsgREVTVElOQVRJT05TICMxMDE8YnI+PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQXJpYWwgOyBmb250LXNpemU6IDEwcHQgOyAiPk5PTEEgQ29kZTogRERERCAxMDEgSEQtQmFzZSBSZXZpc2lvbiAwMDE8YnI+CiAgICAgSEQgRmVlZDogU2F0dXJkYXksIE9jdG9iZXIgMjYsIDIwMTksIDE4MzAtMTkwMEVUIC9IRDAzPGJyPjwvc3Bhbj4KICAgPGJyPgogICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBBcmlhbCA7IGZvbnQtc2l6ZTogMTBwdCA7ICI+MTA6NDQgTWlsbCBjYXJldGFrZXIgk091dGxhdyBEYXZllCB0YWxraW5nIHRvIGhvc3QgTGVzbGllIFNicm9jY28gYXQgdGhlIFN0YW1wIE1pbGwgaW4gVmlyZ2luaWEgQ2l0eTogk1doYXQgdGhlIGhlbGwgYXJlIHlvdSBoZXJlIGZvciB0aGVuP5Q8L3NwYW4+CiAgIDxicj4KICAgPGJyPgogICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBBcmlhbCA7IGZvbnQtc2l6ZTogMTBwdCA7IGZvbnQtd2VpZ2h0OiBib2xkIDsgIj4xMDAgREFZUywgRFJJTktTLCBESVNIRVMgJmFtcDsgREVTVElOQVRJT05TICMxMDI8YnI+PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQXJpYWwgOyBmb250LXNpemU6IDEwcHQgOyAiPk5PTEEgQ29kZTogRERERCAxMDIgSEQtQmFzZSBSZXZpc2lvbiAwMDE8YnI+CiAgICAgSEQgRmVlZDogU2F0dXJkYXksIE5vdmVtYmVyIDIsIDIwMTksIDE4MzAtMTkwMEVUIC9IRDAzPGJyPjwvc3Bhbj4KICAgPGJyPgogICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBBcmlhbCA7IGZvbnQtc2l6ZTogMTBwdCA7ICI+MTA6MTcgSG9zdCBMZXNsaWUgU2Jyb2NjbyBhbmQgTWFydGluIFlhbiB2aXNpdCBhIGJhbyAoc3RlYW1lZCBidW4pIHNob3AgYW5kIHRyeSBhIHZhcmlldHkgb2YgZGlmZmVyZW50IG9wdGlvbnMuICZuYnNwO0xlc2xpZSBqb2tlcywgk1lvdSBjYW4gdGVsbCB3aGF0IG15IGJ1bnMgYXJlIGdvaW5nIHRvIGxvb2sgbGlrZSBhZnRlciBlYXRpbmcgYWxsIHRoZXNlLpQ8L3NwYW4+CiAgIDxicj4KICAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQXJpYWwgOyBmb250LXNpemU6IDEwcHQgOyAiPjExOjQxIJNPaCBteSBHb2SFlDwvc3Bhbj4KICAgPGJyPgogICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBBcmlhbCA7IGZvbnQtc2l6ZTogMTBwdCA7ICI+MTI6MjEgk09oIG15IEdvZCB0aGF0knMgZ29vZIWUPC9zcGFuPgogICA8YnI+CiAgIDxicj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IEFyaWFsIDsgZm9udC1zaXplOiAxMHB0IDsgIj4xNTozMyCTT2ggbXkgR29khZQ8L3NwYW4+CiAgIDxicj4KICAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQXJpYWwgOyBmb250LXNpemU6IDEwcHQgOyAiPjI0OjI1IJNPaCBteSBHb2QgliB0aGF0IGlzIGFtYXppbmculDwvc3Bhbj4KICAgPGJyPgogICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBBcmlhbCA7IGZvbnQtc2l6ZTogMTBwdCA7IGZvbnQtd2VpZ2h0OiBib2xkIDsgIj4xMDAgREFZUywgRFJJTktTLCBESVNIRVMgJmFtcDsgREVTVElOQVRJT05TICMxMDQgQ2FsaXN0b2dhLCBDQTxicj48L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBBcmlhbCA7IGZvbnQtc2l6ZTogMTBwdCA7ICI+Tk9MQSBDb2RlOiBEREREIDEwNCBIRC1CYXNlIFJldmlzaW9uIDAwMTxicj4KICAgICBIRCBGZWVkOiBTYXR1cmRheSwgTm92ZW1iZXIgMTYsIDIwMTksIDE4MzAtMTkwMEVUIC9IRDAzPGJyPjwvc3Bhbj4KICAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQXJpYWwgOyBmb250LXNpemU6IDEwcHQgOyAiPjAyOjA0IEluIGV4cGxhaW5pbmcgaG93IHRoZSB0b3duIG9mIENhbGlzdG9nYSBnb3QgaXRzIG5hbWUsIHRoZSBob3N0IG1pbWljcyBoYXZpbmcgdG9vIG11Y2ggdG8gZHJpbmsgYnkgam9raW5nbHkgc3dheWluZy9zbHVycmluZyB0aGUgd29yZHMgZm9yIGVmZmVjdDo8L3NwYW4+CiAgIDxicj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IEFyaWFsIDsgZm9udC1zaXplOiAxMHB0IDsgIj4gk0FuZCBpbiBhIHRpcHN5IG1vbWVudCwgaW5zdGVhZCBvZiBzYXlpbmcgaXQgd2FzIHRoZSCRU2FyYXRvZ2Egb2YgQ2FsaWZvcm5pYSySIGhlIHNhaWQgaXQgd2FzIHRoZSBDYWxpc3RvZ2Egb2YgU2FyYWZvcm5pYS6UPC9zcGFuPgogICA8YnI+CiAgIDxicj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IEFyaWFsIDsgZm9udC1zaXplOiAxMHB0IDsgIj4yMzo1MCCWIDI1OjEwIFRoZSBob3N0IHZpc2l0cyBhIGxvY2FsIHJlc3RhdXJhbnQgd2hlcmUgdGhlIGNoZWYvb3duZXIgc2hvd3MgaGVyIHRoZWlyIGJhciBzZXQtdXAsIHdpdGggY29ja3RhaWxzIGFuZCB3aW5lIG9uIHRhcC4gJm5ic3A7SGUgcG91cnMgdGhlIGhvc3QgYSBmZXcgZGlmZmVyZW50IGNvY2t0YWlscyB0byBzYW1wbGUuICZuYnNwO0luIGhlciBmaW5hbCBzdGFuZC11cCB0byBjYW1lcmEsIHRoZSBob3N0IGhhcyBhbGwgZm91ciBnbGFzc2VzIGxpbmVkIHVwIG9uIHRoZSBiYXIgYW5kIGNsb3NlcyBvZmYgYnkgc2F5aW5nLCCThSBhbmQgSSBjYW6SdCB0aGluayBvZiBhIGJldHRlciB3YXkgdG8gY2VsZWJyYXRlIHRoZSBwYXN0IGFuZCB0b2FzdCB0aGUgZnV0dXJlIHRoYW4gd2l0aCBhIGNsYXNzaWMgZHJpbmsghSBvciBmb3VyISAmbmJzcDtDaGVlcnMulDwvc3Bhbj4KICAgPGJyPgogICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBBcmlhbCA7IGZvbnQtc2l6ZTogMTBwdCA7ICI+PGJyPjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IEFyaWFsIDsgZm9udC1zaXplOiAxMHB0IDsgZm9udC13ZWlnaHQ6IGJvbGQgOyAiPjEwMCBEQVlTLCBEUklOS1MsIERJU0hFUyAmYW1wOyBERVNUSU5BVElPTlMgIzEwNSBEYW51YmU8YnI+PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQXJpYWwgOyBmb250LXNpemU6IDEwcHQgOyAiPk5PTEEgQ29kZTogRERERCAxMDUgSEQtQmFzZSBSZXZpc2lvbiAwMDE8YnI+CiAgICAgSEQgRmVlZDogU2F0dXJkYXksIE5vdmVtYmVyIDIzLCAyMDE5LCAxODMwLTE5MDBFVCAvSEQwMzwvc3Bhbj4KICAgPGJyPgogICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBBcmlhbCA7IGZvbnQtc2l6ZTogMTBwdCA7ICI+MjI6MzAgQnJvbnplIHN0YXR1ZSBzaG93aW5nIGEgV1dJSS1lcmEgc29sZGllciB3aXRoIGEgbWFjaGluZSBndW4gaG9sZGluZyB1cCBhIGZlbGxvdyBzb2xkaWVyICh3aG8gaXMgd291bmRlZCBvciBkZWFkKS4gJm5ic3A7PC9zcGFuPgogICA8YnI+CiAgIDxicj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IEFyaWFsIDsgZm9udC1zaXplOiAxMHB0IDsgIj4yMjozNSBCcm9uemUgc3RhdHVlIG9mIGEgYmFyZS1icmVhc3RlZCBmZW1hbGUgZmlndXJlLjwvc3Bhbj4KICAgPGJyPgogICA8YnI+CiAgIDxicj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IEFyaWFsIDsgZm9udC1zaXplOiAxMHB0IDsgZm9udC13ZWlnaHQ6IGJvbGQgOyAiPjEwMCBEQVlTLCBEUklOS1MsIERJU0hFUyAmYW1wOyBERVNUSU5BVElPTlMgIzEwNiBBc2hldmlsbGUsIE5DPGJyPjwvc3Bhbj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IEFyaWFsIDsgZm9udC1zaXplOiAxMHB0IDsgIj5OT0xBIENvZGU6IEREREQgMTA2IEhELUJhc2UgUmV2aXNpb24gMDAxPGJyPgogICAgIEhEIEZlZWQ6IFNhdHVyZGF5LCBOb3ZlbWJlciAzMCwgMjAxOSwgMTgzMC0xOTAwRVQgL0hEMDM8L3NwYW4+CiAgIDxicj4KICAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQXJpYWwgOyBmb250LXNpemU6IDEwcHQgOyAiPjA4OjQ0IEJyb256ZSBzdGF0dWUgb2YgYSB5b3VuZyBudWRlIG1hbGUgZmlndXJlIHdyZXN0bGluZyBhIHdpbmdlZCBjcmVhdHVyZS4gJm5ic3A7R2VuaXRhbHMgdmlzaWJsZS48L3NwYW4+CiAgPC9kaXY+CiA8L2JvZHk+CjwvaHRtbD4KLS0wLTVjOGFlOGU2LWM4YjMtNDEyNi1hZjM0LWQxNDhlMWNmNzZjMy0tCg=="
    },
    "ContractConfirmationDescription": {
        "type": "multipart/form-data",
        "topLevelType": "multipart/related",
        "encoding": "BASE64",
        "content": "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvcmVsYXRlZDsgYm91bmRhcnk9MC02Mjc5ZTQ5Yy1mZGI1LTQxYTAtOWEzZi01NzI3NGY2MWQ4ZWUNCgotLTAtNjI3OWU0OWMtZmRiNS00MWEwLTlhM2YtNTcyNzRmNjFkOGVlCkNvbnRlbnQtdHlwZTogdGV4dC9odG1sOyBjaGFyc2V0PVVURi04CkNvbnRlbnQtRGlzcG9zaXRpb246IGlubGluZQo8aHRtbD4KIDxoZWFkPjwvaGVhZD4KIDxib2R5PgogIDxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogVGltZXMgTmV3IFJvbWFuIDsgZm9udC1zaXplOiAxMnB0IDsgIj5JbiB0aGUgY3VsaW5hcnkgYWR2ZW50dXJlIHNlcmllcyAxMDAgREFZUywgRFJJTktTLCBESVNIRVMgJmFtcDsgREVTVElOQVRJT05TLCBKYW1lcyBCZWFyZCBBd2FyZC13aW5uaW5nIHdpbmUgZXhwZXJ0IExlc2xpZSBTYnJvY2NvIHRyYXZlbHMgdGhlIHdvcmxkIHdpdGggZ2xhc3MgYW5kIGZvcmsgaW4gaGFuZCwgaW5kdWxnaW5nIGluIGRlbGljYWNpZXMsIHVuY292ZXJpbmcgbG9jYWwgaGFuZ291dHMsIG1lZXRpbmcgdGFsZW50ZWQgYXJ0aXNhbnMsIGFuZCB2aXNpdGluZyBib3RoIHVwLWFuZC1jb21pbmcgYW5kIGFjY2xhaW1lZCByZXN0YXVyYW50cywgd2luZXJpZXMgYW5kIGJyZXdlcmllcy4gVGhpcyBzZWFzb24sIExlc2xpZSBleHBsb3JlcyBTYW4gRnJhbmNpc2NvknMgQ2hpbmF0b3duIGFuZCBDYWxpc3RvZ2EsIENhbGlmb3JuaWEgYmVmb3JlIGpldHRpbmcgb2ZmIHRvIFZpZW5uYSwgQXVzdHJpYTsgQnVkYXBlc3QsIEh1bmdhcnk7IGFuZCBOb3JtYW5keSwgRnJhbmNlLjwvc3Bhbj4KIDwvYm9keT4KPC9odG1sPgotLTAtNjI3OWU0OWMtZmRiNS00MWEwLTlhM2YtNTcyNzRmNjFkOGVlLS0K"
    },
    "ContractDate": "2019-08-30",
    "ContractEndDate": "2025-10-25",
    "ContractExecuted": "Yes",
    "ContractStartDate": "2019-10-26",
    "ConversionCosts": "",
    "CopyrightDate": "2019",
    "CopyrightHolder": "Tina Salter",
    "CreatePremiere": "",
    "CreatePremiereNotes": "",
    "CreateProgramming": "Yes",
    "CurrentLicensees": 109,
    "DeliveryComments": "",
    "DeliveryDate": "2019-09-06",
    "DescriptionRoutingStatus": "Yes",
    "DigitalClassroom": "No Digital Classroom",
    "Disposition": "Summer RAPID 2019",
    "DistributionDate": "2019-10-26",
    "DoclinkToMerchandise": {
        "type": "multipart/form-data",
        "topLevelType": "multipart/related",
        "encoding": "BASE64",
        "content": "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvcmVsYXRlZDsgYm91bmRhcnk9MC01YTA5M2YwZC02OGU5LTQ4MDQtODk2My04MzljYWU4MjIxNDMNCgotLTAtNWEwOTNmMGQtNjhlOS00ODA0LTg5NjMtODM5Y2FlODIyMTQzCkNvbnRlbnQtdHlwZTogdGV4dC9odG1sOyBjaGFyc2V0PVVURi04CkNvbnRlbnQtRGlzcG9zaXRpb246IGlubGluZQo8aHRtbD4KIDxoZWFkPjwvaGVhZD4KIDxib2R5PjwvYm9keT4KPC9odG1sPgotLTAtNWEwOTNmMGQtNjhlOS00ODA0LTg5NjMtODM5Y2FlODIyMTQzLS0K"
    },
    "DocLinktoOperations": {
        "type": "multipart/form-data",
        "topLevelType": "multipart/related",
        "encoding": "BASE64",
        "content": "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvcmVsYXRlZDsgYm91bmRhcnk9MC03YzUwYzI5ZS1mYTE4LTRhZGYtODU3My1mYzUyMGVjZjk3NTINCgotLTAtN2M1MGMyOWUtZmExOC00YWRmLTg1NzMtZmM1MjBlY2Y5NzUyCkNvbnRlbnQtdHlwZTogdGV4dC9odG1sOyBjaGFyc2V0PVVURi04CkNvbnRlbnQtRGlzcG9zaXRpb246IGlubGluZQo8aHRtbD4KIDxoZWFkPjwvaGVhZD4KIDxib2R5PjwvYm9keT4KPC9odG1sPgotLTAtN2M1MGMyOWUtZmExOC00YWRmLTg1NzMtZmM1MjBlY2Y5NzUyLS0K"
    },
    "Duration": "",
    "EditFlags": "No",
    "EpisodeNumber": "",
    "ExchangeExcludedStations": [
        ""
    ],
    "ExtensionDate": "2022-10-17",
    "FeedNotes": "",
    "FlagsPresent": "Yes",
    "FlagUpdatedDate": "2019-11-20",
    "Formats": [
        "Closed Captioned",
        "Ratio"
    ],
    "IDNumber": 33510,
    "InstallmentNumber1": 1.0,
    "IsPledgeProgram": "",
    "IsReturning": "",
    "LastUpdatedByAgent": "",
    "Limitations": "",
    "LinearLiveStreaming": "Yes",
    "LocalUnderwritingPermitted": "Yes",
    "LocalUnderwritingRestrictions": "Provided that the local underwriter is not competitive with the national underwriter",
    "MainContact": "Aine Henderson, KQED\r\nahenderson@kqed.org\r\n415-553-2437\r\n\r\nProducer: Tina Salter, 100 Days Productions\r\ntima@100daysproductions.com\r\n415-860-5088",
    "Material": "Yes",
    "MediaContact": "",
    "MMAdminUrl": "",
    "MMAssetComments": "",
    "MMDescriptionsReviewed": "Reviewed",
    "MMEPiC": "Undetermined",
    "MMGeneralstreaming": "Undetermined",
    "MMGeneralStreamingGeo": "US & Territories",
    "MMGenre": "",
    "MMLongDesc": "James Beard Award-winning wine expert Leslie Sbrocco travels the world with glass and fork in hand, indulging in delicacies, uncovering local hangouts, meeting talented artisans and visiting both up-and-coming and acclaimed restaurants, wineries and breweries. Leslie explores San Francisco’s Chinatown and Calistoga, CA, before jetting off to Vienna, Budapest, and Normandy.",
    "MMPassportStreaming": "Undetermined",
    "MMPassportStreamingGeo": "US & Territories",
    "MMPotential": "Not determined",
    "MMPublicURL": "",
    "MMPublished": "",
    "MMPublisher": "Not determined",
    "MMShortDesc": "James Beard Award-winning wine expert Leslie Sbrocco travels the world.",
    "MMShowPageStatus": "-",
    "MMShowTypeAudience": "",
    "Modified": "2022-10-17T12:06:21-05:00",
    "MusicCueSheet": "No",
    "NationalDistributionExclusivity": "Yes",
    "NationalUnderwriter": "Yes",
    "NCCComments": "",
    "NewSeasonAwards": "",
    "NewSeasonInfo": "",
    "NewSeasonSuccesses": "",
    "NolaCode": "DDDD",
    "NoncommercialCable": "Noncommercial Cable",
    "NumberOfEpisodes": "6",
    "OfferDescription": {
        "type": "multipart/form-data",
        "topLevelType": "multipart/related",
        "encoding": "BASE64",
        "content": "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvcmVsYXRlZDsgYm91bmRhcnk9MC02ZjQ2NzQyZS04M2M5LTQ3ZTctOGNlMi01ZDUyNTJjMTM0YjENCgotLTAtNmY0Njc0MmUtODNjOS00N2U3LThjZTItNWQ1MjUyYzEzNGIxCkNvbnRlbnQtdHlwZTogdGV4dC9odG1sOyBjaGFyc2V0PVVURi04CkNvbnRlbnQtRGlzcG9zaXRpb246IGlubGluZQo8aHRtbD4KIDxoZWFkPjwvaGVhZD4KIDxib2R5PgogIDxicj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IENhbGlicmkgOyBmb250LXNpemU6IDEycHQgOyAiPkluIGhlciBuZXcgY3VsaW5hcnkgYWR2ZW50dXJlIHNlcmllcyAxMDAgREFZUywgRFJJTktTLCBESVNIRVMgJmFtcDsgREVTVElOQVRJT05TLCBKYW1lcyBCZWFyZCBBd2FyZC13aW5uaW5nIHdpbmUgZXhwZXJ0IExlc2xpZSBTYnJvY2NvIHRyYXZlbHMgdGhlIHdvcmxkIHdpdGggZ2xhc3MgYW5kIGZvcmsgaW4gaGFuZCwgaW5kdWxnaW5nIGluIGRlbGljYWNpZXMsIHVuY292ZXJpbmcgbG9jYWwgaGFuZ291dHMsIGRpc2NvdmVyaW5nIHRhbGVudGVkIGFydGlzYW5zLCBhbmQgdmlzaXRpbmcgYm90aCB1cC1hbmQtY29taW5nIGFuZCBhY2NsYWltZWQgcmVzdGF1cmFudHMsIHdpbmVyaWVzIGFuZCBicmV3ZXJpZXMuPC9zcGFuPgogIDxicj4KICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBDYWxpYnJpIDsgZm9udC1zaXplOiAxMnB0IDsgIj5UaGlzIHNlYXNvbiwgTGVzbGllIHNpcHMgQ2FsdmFkb3MgZnJvbSB0aGUgYXBwbGUgb3JjaGFyZHMgb2YgTm9ybWFuZHksIEZyYW5jZSBhbmQgdGFzdGVzIHRoZSBjb21wbGV4aXR5IG9mIGxvY2FsIENhbWVtYmVydCBjaGVlc2UuIFNoZSB0aGVuIHVuY292ZXJzIHRoZSBwZXJmZWN0IHN1bm55IGJlYWNoIGZvciBhIHBpY25pYyBpbiBsYW5kLWxvY2tlZCBBdXN0cmlhIGFuZCB0YWtlcyBpbiB0aGUgZHJhbWF0aWMgYXJjaGl0ZWN0dXJlIG9uIFZpZW5uYSdzIFJpbmdzdHJhc3NlLjwvc3Bhbj4KICA8YnI+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+QSBDYWxpZm9ybmlhIG5hdGl2ZSwgTGVzbGllIGFsc28gZXhwbG9yZXMgdGhlIEdvbGRlbiBTdGF0ZSBmcm9tIGFuIGluc2lkZXIncyBwZXJzcGVjdGl2ZS4gU2hlIG1lZXRzIHVwIHdpdGggY2hlZiBNYXJ0aW4gWWFuIGZvciBhIHRhc3R5IHRvdXIgb2YgU2FuIEZyYW5jaXNjbydzIENoaW5hdG93biwgc2FtcGxpbmcgc3RlYW1lZCBiYW8sIGRyYWdvbiBiZWFyZCBjYW5keSBhbmQgY2xhc3NpYyBkaW0gc3VtLiBNb3Zpbmcgbm9ydGggdG8gQ2FsaXN0b2dhLCBzaGUgbGVhcm5zIGhvdyB0aGUgYW5jaWVudCBob3Qgc3ByaW5ncyBhbmQgdm9sY2FuaWMgcm9jayBvZiB0aGUgcmVnaW9uIGRlZmluZSBtb2Rlcm4gdmluZXlhcmRzIGFuZCBnZXRzIGEgbGVzc29uIGF0IGEgbG9jYWwgcG90dGVyJ3Mgd2hlZWwuICZuYnNwOzwvc3Bhbj4KICA8YnI+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+SW4gQnVkYXBlc3QsIExlc2xpZSByZWxheGVzIGluIG5hdHVyYWwgc3BhcyBhbmQgdHJpZXMgY3VsaW5hcnkgZGVsaWdodHMgZnJvbSBtYW5nYWxpdHNhIHRvIGdvdWxhc2guIFRoZW4gc2hlIGhlYWRzIG91dCB0byB0aGUgY291bnRyeXNpZGUgb2YgVG9rYWosIEh1bmdhcnksIHdoZXJlIHNoZSB3YWxrcyB0aGUgY2VudHVyaWVzLW9sZCBwYXRoIG9mIHRoZSBKZXdpc2ggd2luZSB0cmFkZS4gRmluYWxseSwgTGVzbGllIGhpdHMgdXAgTmFzaHZpbGxlLCBUZW5uZXNzZWUgd2l0aCB0d28gbG9jYWxzIGZyb20gdGhlIG11c2ljIGluZHVzdHJ5IHRvIHNjb3BlIG91dCB0aGUgYmVzdCB0dW5lcyBhbmQgdGFzdGVzLCBmcm9tIGZyaWVkIG95c3RlcnMgaW4gYSBob25reSB0b25rIGJhciB0byBhbiBlbWVyZ2luZyBib3VyYm9uIGluZHVzdHJ5IG9uIHRoZSBvdXRza2lydHMgb2YgdGhlIGNpdHkuICZuYnNwOzwvc3Bhbj4KICA8YnI+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+RXBpc29kZXMgaW5jbHVkZTo8L3NwYW4+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+IkNoaW5hdG93biwgU2FuIEZyYW5jaXNjbywgQ2FsaWZvcm5pYSI8L3NwYW4+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+IkNhbGlzdG9nYSwgQ2FsaWZvcm5pYSI8L3NwYW4+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+IlZpZW5uYSwgQXVzdHJpYSI8L3NwYW4+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+IkJ1ZGFwZXN0IGFuZCBUb2thaiwgSHVuZ2FyeSI8L3NwYW4+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+Ik5vcm1hbmR5LCBGcmFuY2UiPC9zcGFuPgogIDxicj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IENhbGlicmkgOyBmb250LXNpemU6IDEycHQgOyAiPiJOYXNodmlsbGUsIFRlbm5lc3NlZSI8L3NwYW4+CiAgPGJyPgogIDxicj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IENhbGlicmkgOyBmb250LXNpemU6IDEycHQgOyBmb250LXdlaWdodDogYm9sZCA7ICI+Rk9STUFUOiA8L3NwYW4+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+NngzMCBIRC1CYXNlPC9zcGFuPgogIDxicj4KICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBDYWxpYnJpIDsgZm9udC1zaXplOiAxMnB0IDsgZm9udC13ZWlnaHQ6IGJvbGQgOyAiPkxJTkVBUiBMSVZFIFNUUkVBTUlORyBSSUdIVFM6PC9zcGFuPgogIDxicj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6IENhbGlicmkgOyBmb250LXNpemU6IDEycHQgOyAiPkxpbmVhciBMaXZlIFN0cmVhbWluZyByaWdodHMgYXJlIGdyYW50ZWQuPC9zcGFuPgogIDxicj4KICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBDYWxpYnJpIDsgZm9udC1zaXplOiAxMnB0IDsgZm9udC13ZWlnaHQ6IGJvbGQgOyAiPlJJR0hUUyBOT1RFOiA8L3NwYW4+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+Tm9uLWV4Y2x1c2l2ZSBmdWxsIHByb2dyYW0gc3RyZWFtaW5nIHJpZ2h0cyBhcmUgZ3JhbnRlZCBmb3Igc3RhdGlvbiB3ZWJzaXRlcyBmb3IgdGhlIGxpY2Vuc2VkIHBlcmlvZC4gPC9zcGFuPgogIDxicj4KICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBDYWxpYnJpIDsgZm9udC1zaXplOiAxMnB0IDsgZm9udC13ZWlnaHQ6IGJvbGQgOyAiPlVOREVSV1JJVEVSUzo8L3NwYW4+CiAgPGJyPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogQ2FsaWJyaSA7IGZvbnQtc2l6ZTogMTJwdCA7ICI+QU1BIFdhdGVyd2F5czwvc3Bhbj4KICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBDYWxpYnJpIDsgZm9udC1zaXplOiAxMnB0IDsgIj5ZZWxsb3cgVGFpbDwvc3Bhbj4KICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBDYWxpYnJpIDsgZm9udC1zaXplOiAxMnB0IDsgIj5Kb3NoIFdpbmVzPC9zcGFuPgogIDxicj4KICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBDYWxpYnJpIDsgZm9udC1zaXplOiAxMnB0IDsgZm9udC13ZWlnaHQ6IGJvbGQgOyAiPlVOREVSV1JJVElORyBOT1RFOjwvc3Bhbj4KICA8YnI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBDYWxpYnJpIDsgZm9udC1zaXplOiAxMnB0IDsgIj5Mb2NhbCB1bmRlcndyaXRpbmcgaXMgcGVybWlzc2libGUuIExvY2FsIHVuZGVyd3JpdGVycyBtdXN0IG5vdCBjb21wZXRlIHdpdGggdGhlIG5hdGlvbmFsIHVuZGVyd3JpdGVycyBvZiB0aGlzIHByb2dyYW0uPC9zcGFuPgogPC9ib2R5Pgo8L2h0bWw+Ci0tMC02ZjQ2NzQyZS04M2M5LTQ3ZTctOGNlMi01ZDUyNTJjMTM0YjEtLQo="
    },
    "OfferDescription_1": {
        "type": "multipart/form-data",
        "topLevelType": "multipart/related",
        "encoding": "BASE64",
        "content": "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvcmVsYXRlZDsgYm91bmRhcnk9MC01YzEzYTkwYy0yYWMyLTQ3Y2EtOGNhYy0wYTgxMzA1MjBhOWQNCgotLTAtNWMxM2E5MGMtMmFjMi00N2NhLThjYWMtMGE4MTMwNTIwYTlkCkNvbnRlbnQtdHlwZTogdGV4dC9odG1sOyBjaGFyc2V0PVVURi04CkNvbnRlbnQtRGlzcG9zaXRpb246IGlubGluZQo8aHRtbD4KIDxoZWFkPjwvaGVhZD4KIDxib2R5PjwvYm9keT4KPC9odG1sPgotLTAtNWMxM2E5MGMtMmFjMi00N2NhLThjYWMtMGE4MTMwNTIwYTlkLS0K"
    },
    "OfferStatus": "",
    "OfferType": [
        "Teleconference"
    ],
    "OperationsContact": "",
    "Other": {
        "type": "multipart/form-data",
        "topLevelType": "multipart/related",
        "encoding": "BASE64",
        "content": "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvcmVsYXRlZDsgYm91bmRhcnk9MC0xOTk4ZTk5Ni0zN2Q5LTRmYWQtOTBiNi1lNGM2YWQxMWRjZWINCgotLTAtMTk5OGU5OTYtMzdkOS00ZmFkLTkwYjYtZTRjNmFkMTFkY2ViCkNvbnRlbnQtdHlwZTogdGV4dC9odG1sOyBjaGFyc2V0PVVURi04CkNvbnRlbnQtRGlzcG9zaXRpb246IGlubGluZQo8aHRtbD4KIDxoZWFkPjwvaGVhZD4KIDxib2R5PjwvYm9keT4KPC9odG1sPgotLTAtMTk5OGU5OTYtMzdkOS00ZmFkLTkwYjYtZTRjNmFkMTFkY2ViLS0K"
    },
    "OtherMedia": [
        ""
    ],
    "OtherPeriodDuration": "",
    "PageNumber": "E5",
    "PayableComments": "",
    "PgmRelatedMerch": "",
    "PledgeFriendly": "",
    "Presentation": "No",
    "PresentedBy": "KQED",
    "PressStationAgreement": "",
    "PricingStructure": "",
    "ProdOrgEIDRID": "",
    "ProducedBy": "100 Days Production via KQED",
    "ProducerServicesFee": 1680.0,
    "ProductionDate": "2019",
    "ProductOfferTag": "",
    "ProgramComments": "10/17/2022 - License term is extended for a period of three (3) years with a revised end date of October 25, 2025. Broadcast rights are unlimited use including one year school re-record, simulcast, video on demand, and non-commercial cable rights. New media and Linear Live Streaming rights are granted. (shj)",
    "ProgramEIDRID": "",
    "ProgramFund": "",
    "ProgramLength": [
        "30"
    ],
    "ProgramLengthPledgeEvent": "",
    "ProgramService": "Exchange",
    "ProgramStatus": "Contract",
    "ProgramSummary": "",
    "ProgramTitle": "",
    "ProjectedReleaseDate": "Saturday, October 26, 2019 (RAPID)",
    "PromoComments": "30",
    "PromosAvailable": "Yes",
    "PromotionalMaterials": [
        "Visit APTonline.org to download a press release",
        "host bio",
        "episode listings",
        "photography and a broadcast promo",
        "and to access an embeddable web promo."
    ],
    "PromotionalResources": "",
    "PSFCallLetters": "KQED",
    "PSFExported": "Yes",
    "PTVGenre": "",
    "PursuedBy": "",
    "Rating": "TV-G",
    "Ratio": "16:9",
    "ReRecordLength": "1 year",
    "RevenueSharing": "No",
    "RevenueSharingComments": {
        "type": "multipart/form-data",
        "topLevelType": "multipart/related",
        "encoding": "BASE64",
        "content": "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvcmVsYXRlZDsgYm91bmRhcnk9MC04MWZlNzY3My1mMTI4LTRjZTQtOWYyMy0zNTk1ODQ1NjlmYzINCgotLTAtODFmZTc2NzMtZjEyOC00Y2U0LTlmMjMtMzU5NTg0NTY5ZmMyCkNvbnRlbnQtdHlwZTogdGV4dC9odG1sOyBjaGFyc2V0PVVURi04CkNvbnRlbnQtRGlzcG9zaXRpb246IGlubGluZQo8aHRtbD4KIDxoZWFkPjwvaGVhZD4KIDxib2R5PjwvYm9keT4KPC9odG1sPgotLTAtODFmZTc2NzMtZjEyOC00Y2U0LTlmMjMtMzU5NTg0NTY5ZmMyLS0K"
    },
    "RSFCallLetters": "",
    "RSFExported": "No",
    "Sales": "No",
    "SchedulingSuggestions": [
        ""
    ],
    "SchoolReRecord": "School Rerecord",
    "ScreeningStatus": "",
    "SeasonYear": "",
    "SeriesIDNumber": "APTEXCH10447",
    "SeriesTitle": "100 DAYS, DRINKS, DISHES & DESTINATIONS",
    "Simulcast": "Simulcast",
    "SimulcastComments": "",
    "sIXAvailability": "yes",
    "StationRelationsContact": "",
    "Streaming": "",
    "Streaming3rdPartyExcerpts": "Yes",
    "Streaming3rdPartyExcerptsHH": 0.0,
    "Streaming3rdPartyExcerptsMM": 3.0,
    "Streaming3rdPartyExcerptsSS": 0.0,
    "Streaming3rdPartyFullVersion": "No",
    "Streaming3rdPartyShortFormat": "",
    "Streaming3rdPartyShortFormatHH": 0.0,
    "Streaming3rdPartyShortFormatMM": 0.0,
    "Streaming3rdPartyShortFormatSS": 0.0,
    "StreamingDesc": "",
    "StreamingDownloadToOwn": "No",
    "StreamingIPTVChannels": "No",
    "StreamingMobileExcerpts": "Yes",
    "StreamingMobileExcerptsHH": 0.0,
    "StreamingMobileExcerptsMM": 3.0,
    "StreamingMobileExcerptsSS": 0.0,
    "StreamingMobileFullVersion": "No",
    "StreamingMobileShortFormat": "",
    "StreamingMobileShortFormatHH": 0.0,
    "StreamingMobileShortFormatMM": 0.0,
    "StreamingMobileShortFormatSS": 0.0,
    "StreamingProtected": "Yes",
    "StreamingPublicExcerpts": "No",
    "StreamingPublicExcerptsHH": 0.0,
    "StreamingPublicExcerptsMM": 0.0,
    "StreamingPublicExcerptsSS": 0.0,
    "StreamingPublicFullVersion": "No",
    "StreamingPublicShortFormat": "",
    "StreamingPublicShortFormatHH": 0.0,
    "StreamingPublicShortFormatMM": 0.0,
    "StreamingPublicShortFormatSS": 0.0,
    "SubmissionForm": "Yes",
    "SubmittedFrom": "",
    "SupplierCompany": "KQED",
    "SupplierEmail": "",
    "SupplierFilesReceived": "",
    "TapeInHouse": [
        "Screening link",
        "File-Program"
    ],
    "TempVotes": "",
    "Title": "100 DAYS, DRINKS, DISHES & DESTINATIONS",
    "UnderwrittenBy": "",
    "UpTempo": "No",
    "USPremiere": "No",
    "Video": "",
    "ViewerInquiries": "KQED Audience Services\r\nPhone: (415) 553-2150\r\nEmail: vwrserv@kqed.org \r\n\r\nLeslie Sbrocco\r\nTwitter: https://twitter.com/lesliesbrocco \r\nInstagram: https://www.instagram.com/lesliesbrocco \r\nPinterest: https://www.pinterest.com/lesliesbrocco ",
    "VOD": "Yes",
    "VODComments": "",
    "WebFeeExported": "No",
    "WebMarkers": "",
    "websiteproductsfee": 0.0,
    "WebTag": "",
    "WorkflowSource": "",
    "WorkingTitle": "",
    "WorldPremiere": "",
    "WorldPremiereNotes": "",
    "WorldProgramming": "No",
    "WPOFCallLetters": "",
    "yesCallSigns": [
        "KAET",
        "KAID",
        "KAKM",
        "KBDI",
        "KCTS",
        "KCWC",
        "KDIN",
        "KEET",
        "KENW",
        "KERA",
        "KFME",
        "KLCS",
        "KLRU",
        "KLVX",
        "KNME",
        "KNPB",
        "KOCE",
        "KOPB",
        "KPBS",
        "KPTS",
        "KQED",
        "KQED",
        "KRCB",
        "KRMA",
        "KSPS",
        "KSYS",
        "KTCA",
        "KTTZ",
        "KTWU",
        "KUAC",
        "KUAT",
        "KUED",
        "KUHT",
        "KUON",
        "KUSM",
        "KVCR",
        "KVPT",
        "KWCM",
        "KWSU",
        "WBIQ",
        "WBRA",
        "WCFE",
        "WCMU",
        "WCNY",
        "WCTE",
        "WCVE",
        "WEDH",
        "WEDU",
        "WEIU",
        "WETK",
        "WFSU",
        "WFWA",
        "WFYI",
        "WGBY",
        "WGTE",
        "WGVU",
        "WHRO",
        "WHUT",
        "WHYY",
        "WIPB",
        "WITF",
        "WJCT",
        "WKAR",
        "WKLE",
        "WKYU",
        "WLIW",
        "WLPB",
        "WLRN",
        "WLVT",
        "WMHT",
        "WMPB",
        "WMPN",
        "WMVS",
        "WNED",
        "WNEO",
        "WNET",
        "WNIT",
        "WNJT",
        "WNPT",
        "WOUB",
        "WPBA",
        "WPBS",
        "WPBT",
        "WPNE",
        "WPSU",
        "WQED",
        "WQPT",
        "WRLK",
        "WSBE",
        "WSIU",
        "WSKG",
        "WSRE",
        "WTIU",
        "WTTW",
        "WTVI",
        "WTVS",
        "WUFT",
        "WUNC",
        "WVPT",
        "WXEL",
        "WYES",
        "WYIN"
    ],
    "Form": "Program",
    "@warnings": [
        "No values found for item AdministrativeSurcharge",
        "No values found for item BillingStartDate",
        "No values found for item BlackoutPeriod",
        "No values found for item ContainsFiller",
        "No values found for item Created",
        "No values found for item DaysBetweenInstallments",
        "No values found for item EffectiveDate",
        "No values found for item FillerMaxLength",
        "No values found for item FillerMinLength",
        "No values found for item GuaranteedPrice",
        "No values found for item InstallmentAmount1",
        "No values found for item InstallmentAmount10",
        "No values found for item InstallmentAmount11",
        "No values found for item InstallmentAmount12",
        "No values found for item InstallmentAmount2",
        "No values found for item InstallmentAmount3",
        "No values found for item InstallmentAmount4",
        "No values found for item InstallmentAmount5",
        "No values found for item InstallmentAmount6",
        "No values found for item InstallmentAmount7",
        "No values found for item InstallmentAmount8",
        "No values found for item InstallmentAmount9",
        "No values found for item InstallmentDate1",
        "No values found for item InstallmentDate10",
        "No values found for item InstallmentDate11",
        "No values found for item InstallmentDate12",
        "No values found for item InstallmentDate2",
        "No values found for item InstallmentDate3",
        "No values found for item InstallmentDate4",
        "No values found for item InstallmentDate5",
        "No values found for item InstallmentDate6",
        "No values found for item InstallmentDate7",
        "No values found for item InstallmentDate8",
        "No values found for item InstallmentDate9",
        "No values found for item InstallmentNumber10",
        "No values found for item InstallmentNumber11",
        "No values found for item InstallmentNumber12",
        "No values found for item InstallmentNumber2",
        "No values found for item InstallmentNumber3",
        "No values found for item InstallmentNumber4",
        "No values found for item InstallmentNumber5",
        "No values found for item InstallmentNumber6",
        "No values found for item InstallmentNumber7",
        "No values found for item InstallmentNumber8",
        "No values found for item InstallmentNumber9",
        "No values found for item LiveStreamingInDiscussionDate",
        "No values found for item MMGeneralEndDate",
        "No values found for item MMGeneralStartDate",
        "No values found for item MMPassportEndDate",
        "No values found for item MMPassportStartDate",
        "No values found for item MMPublishedDate",
        "No values found for item NationalBasePrice",
        "No values found for item NumberOfInstallments",
        "No values found for item PaymentToSupplier",
        "No values found for item PerProgramMinimum",
        "No values found for item PremiumYear",
        "No values found for item ProgramLengthPledge",
        "No values found for item PSNonMemberAdminSurcharge",
        "No values found for item Release",
        "No values found for item RevenueSharingAmount",
        "No values found for item RevenueSharingFee",
        "No values found for item Season",
        "No values found for item SupplierFilesReceivedDate",
        "No values found for item UpdatedBy"
    ]
}